# Generated by Django 4.1.3 on 2023-05-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.BooleanField(default=False),
        ),
    ]
