repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
      language_version: python3
    - id: no-commit-to-branch
      args: ['--branch', 'development', '--branch', 'staging', '--branch', 'production']


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: local
  hooks:
    - id: djlint-reformat
      name: djlint-reformat
      entry: uv run djlint --reformat
      language: system
      types: [html]
    - id: djlint-check
      name: djlint-check
      entry: uv run djlint --check
      language: system
      types: [html]
