# Generated by Django 4.1.3 on 2023-05-02 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                ("religion", models.CharField(max_length=50)),
                ("nationality", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=50)),
                ("nid_no", models.IntegerField()),
                ("nid_image", models.ImageField(upload_to="images/nid")),
                ("birth_date", models.DateField()),
                ("website", models.CharField(blank=True, max_length=70, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=50, null=True)),
                ("about", models.TextField()),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="images/man.png",
                        null=True,
                        upload_to="images/profile",
                    ),
                ),
                ("present_address", models.CharField(max_length=100)),
                ("permanent_address", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Married", "Married"),
                            ("Unmarried", "Unmarried"),
                            ("Devorced", "Devorced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("employer", "Employer"), ("jobseeker", "Job Seeker")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
