# Generated by Django 4.1.3 on 2023-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_userprofile_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="background_profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/profile_background.jpg",
                null=True,
                upload_to="images/background-profile",
            ),
        ),
    ]
