# Generated by Django 4.1.3 on 2023-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userprofile_background_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="background_profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/background-profile"
            ),
        ),
    ]
