# Generated by Django 4.1.3 on 2023-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_userprofile_background_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="background_profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/default/background-profile"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/default/man.png",
                null=True,
                upload_to="images/profile",
            ),
        ),
    ]
