# Generated by Django 4.1.3 on 2023-05-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_education_bsc_cgpa_alter_education_hsc_cgpa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="msc_cgpa",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
