# Generated by Django 4.1.3 on 2023-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_education_msc_cgpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="bsc_graduation_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
