# Generated by Django 4.1.3 on 2023-05-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_education"),
        ("main", "0006_alter_education_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducation",
                to="accounts.userprofile",
            ),
        ),
    ]
