# Generated by Django 4.1.3 on 2023-05-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_education"),
        ("main", "0008_education_bsc_certificate_education_hsc_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="bsc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="applicant/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="hsc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="applicant/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="msc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="applicant/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="ssc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="applicant/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducation",
                to="accounts.userprofile",
            ),
        ),
    ]
