# Generated by Django 4.1.3 on 2023-05-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_education_bsc_certificate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
    ]
