# Generated by Django 4.1.3 on 2023-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_conversationmessages_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
