# Generated by Django 4.1.3 on 2023-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_review_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="show",
            field=models.BooleanField(default=False),
        ),
    ]
