# Generated by Django 4.1.3 on 2023-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_email",
            field=models.EmailField(default="mdzayed2019@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
