# Generated by Django 4.1.3 on 2023-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_job_company_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="image",
        ),
        migrations.AddField(
            model_name="job",
            name="company_image",
            field=models.ImageField(
                blank=True,
                default="images/default/default.jpg",
                null=True,
                upload_to="jobs/image",
            ),
        ),
    ]
