# Generated by Django 4.1.3 on 2023-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_remove_job_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="application",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.application",
            ),
            preserve_default=False,
        ),
    ]
