# Generated by Django 4.2.5 on 2025-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_aboutpage_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
