# Generated by Django 4.1.3 on 2023-05-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="hsc_cgpa",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="education",
            name="hsc_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="msc_graduation_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="ssc_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
