# Generated by Django 4.1.3 on 2023-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_education_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="bsc_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applicant/certificate/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="hsc_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applicant/certificate/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="msc_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applicant/certificate/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="ssc_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applicant/certificate/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
    ]
